{"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3.12"}, "changed": true, "cmd": "getent passwd | cut -d: -f1", "delta": "0:00:00.002345", "end": "2025-08-10 16:48:39.676741", "msg": "", "rc": 0, "start": "2025-08-10 16:48:39.674396", "stderr": "", "stderr_lines": [], "stdout": "root\ndaemon\nbin\nsys\nsync\ngames\nman\nlp\nmail\nnews\nuucp\nproxy\nwww-data\nbackup\nlist\nirc\n_apt\nnobody\nsystemd-network\nsystemd-timesync\ndhcpcd\nmessagebus\nsystemd-resolve\npollinate\npolkitd\nsyslog\nuuidd\ntcpdump\nlandscape\nfwupd-refresh\nsshd\nuser1", "stdout_lines": ["root", "daemon", "bin", "sys", "sync", "games", "man", "lp", "mail", "news", "uucp", "proxy", "www-data", "backup", "list", "irc", "_apt", "nobody", "systemd-network", "systemd-timesync", "dhcpcd", "messagebus", "systemd-resolve", "pollinate", "polkitd", "syslog", "uuidd", "tcpdump", "landscape", "fwupd-refresh", "sshd", "user1"], "warnings": ["Platform linux on host ubuntu1 is using the discovered Python interpreter at /usr/bin/python3.12, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html for more information."]}